// Generated by CoffeeScript 1.6.2
(function() {
  var applescript, move, print, record, run;

  applescript = require('applescript');

  move = require('./util').move;

  print = console.log;

  record = function(secs, file) {
    var script;

    if (secs == null) {
      secs = 5;
    }
    script = "tell application \"QuickTime Player\"\n  activate\n  close every window saving no\n  set audioRecording to (new audio recording)\n  tell audioRecording\n    start\n    delay " + secs + "\n    stop\n  end tell\n  save\n  close every window saving no\nend tell\ntell application \"Terminal\"\n  activate\nend tell";
    return applescript.execString(script, function(err, r) {
      if (err) {
        return print("error!");
      } else {
        if (r) {
          print(r);
        }
        return move('~/Movies/Audio*Recording.*', file, function(err) {
          if (err) {
            return print(err);
          } else {
            return print("Created " + file + " with " + secs + " seconds of audio!");
          }
        });
      }
    });
  };

  run = function() {
    'Run as a command-line script.\n  ';
    var argv, file, target;

    argv = require('optimist').alias('t', 'time')["default"]('t', 5).describe('t', 'Time in seconds to record').argv;
    file = argv._[0];
    target = file != null ? file + ".mov" : __dirname + "/audio.mov";
    return record(argv.time, target);
  };

  module.exports = {
    run: run,
    record: record
  };

}).call(this);
