// Generated by CoffeeScript 1.6.2
/*
handy - record and view motion capture samples.

USAGE

  handy --record NUMBER_OF_FRAMES [FILENAME]
  handy FILENAME

  handy -r 1000                # stream 1000 frames to stdout 
  handy -r 1000 sample.json    # stream 1000 frames to sample.json
  handy sample.json            # view sample.json
*/


(function() {
  var audio, data, fs, minty, open, path, print, run, save, serve, time, view;

  fs = require('fs');

  path = require('path');

  time = require('./time');

  audio = require('./audio');

  minty = require('./minty');

  open = require('./util').open;

  print = console.log;

  data = {};

  save = function(frames, file) {
    'Save a specified number of motion frames as a sample to file.\n  ';
    var WebSocket, i, max, out, ws;

    WebSocket = require('ws');
    ws = new WebSocket('ws://localhost:6437');
    out = file ? fs.createWriteStream(file) : process.stdout;
    max = parseInt(frames);
    i = 0;
    ws.on('open', function() {
      if (file) {
        print(' leap socket opened');
      }
      ws.send(JSON.stringify({
        enableGestures: true
      }));
      return out.write('[\n');
    });
    ws.on('close', function(code, reason) {
      out.write(']\n');
      if (file) {
        print(' leap socket closed');
        print(" " + ws.bytesReceived + " bytes received");
        print(" " + max + " frames written to " + file);
        time.info(file);
        if (reason) {
          return print(reason);
        }
      }
    });
    ws.on('error', function(err) {
      return print(err);
    });
    return ws.on('message', function(d) {
      if (i === 0) {
        print(" version " + (JSON.parse(d).version));
      } else if (max > i) {
        out.write("" + d + ",\n");
      } else if (max === i) {
        out.write("" + d + "\n");
      } else {
        ws.close();
      }
      return i += 1;
    });
  };

  view = function(file) {
    'View sample file.';    if (!file) {
      return print('Please specify a sample file to view');
    } else {
      print("Timing info for " + file + ":");
      return time.info(file);
    }
  };

  serve = function(page) {
    var http, server;

    http = require('http');
    server = http.createServer(function(req, res) {
      res.writeHead(200, {
        'Content-Type': 'text/html',
        'Content-Length': page.length
      });
      return res.end(page);
    });
    server.listen(8080, function() {
      return setTimeout((function() {
        return server.close();
      }), 5000);
    });
    return open("http://localhost:8080");
  };

  run = function() {
    'Run as a command-line script.\n  ';
    var argv, audioFile, file, fps, frames, handsFile, secs, viewFile, viewPage;

    argv = require('optimist').alias('a', 'audio').alias('t', 'time').alias('v', 'view').describe('t', 'Time in seconds to record').describe('a', 'Record and save audio track').describe('v', 'View recorded sample in a web browser').argv;
    fps = 90;
    secs = 5;
    handsFile = 'sample.json';
    audioFile = 'sample.mov';
    viewFile = 'sample.html';
    if (argv._) {
      file = argv._[0];
      handsFile = file + '.json';
      audioFile = file + '.mov';
      viewFile = file + '.html';
    }
    if (argv.time) {
      secs = argv.time;
      frames = secs * fps;
      if (argv.audio) {
        audio.record(secs, audioFile);
      }
      save(frames, handsFile);
    } else {
      view(file);
    }
    if (argv.view) {
      data = {
        file: {
          leap: path.basename(handsFile),
          audio: path.basename(audioFile)
        },
        script: {
          view: fs.readFileSync(__dirname + '/../template/view.js', 'utf8')
        }
      };
      viewPage = minty.renderFile(__dirname + '/../template/view.cst', data);
      return fs.writeFile(viewFile, viewPage, function(err) {
        if (err) {
          print(err);
        }
        return print("Created " + viewFile + " for viewing sample");
      });
    }
  };

  module.exports = {
    run: run,
    save: save,
    view: view
  };

}).call(this);
