// Generated by CoffeeScript 1.6.2
(function() {
  var coffee, fs, render, renderFile;

  fs = require('fs');

  coffee = require('coffee-script');

  render = function(text, data) {
    var f, t;

    t = text.replace(/\n/g, '\\n').replace(/"/g, '\\"');
    f = coffee["eval"]('(data) -> "' + t + '"');
    if (data) {
      return f(data);
    } else {
      return f;
    }
  };

  renderFile = function(file, data) {
    var source;

    source = fs.readFileSync(file, 'utf8').toString();
    return render(source, data);
  };

  module.exports = {
    render: render,
    renderFile: renderFile
  };

}).call(this);
