// Generated by CoffeeScript 1.6.2
(function() {
  var calc, fs, print, show;

  fs = require('fs');

  print = console.log;

  calc = function(data) {
    'Calculate timing info for data sample.';
    var frames, info, last, secs, start, stop;

    frames = JSON.parse(data);
    last = frames.length - 1;
    start = frames[0].timestamp;
    stop = frames[last].timestamp;
    secs = (stop - start) / 1000000;
    return info = {
      frames: frames.length,
      seconds: secs,
      FPS: frames.length / secs
    };
  };

  show = function(err, data) {
    'Print timing info for data sample.';    if (err) {
      return print(err);
    } else {
      return print(calc(data));
    }
  };

  exports.info = function(file, done) {
    if (done == null) {
      done = show;
    }
    return fs.readFile(file, 'utf8', done);
  };

}).call(this);
