// Generated by CoffeeScript 1.6.2
(function() {
  var exec, move, open, print;

  exec = require('child_process').exec;

  print = console.log;

  move = function(source, target, err_handler) {
    if (err_handler == null) {
      err_handler = print;
    }
    return exec("mv " + source + " " + target, function(err) {
      return err_handler(err);
    });
  };

  open = function(file, err_handler) {
    if (err_handler == null) {
      err_handler = print;
    }
    return exec("open " + file, function(err) {
      return err_handler(err);
    });
  };

  module.exports = {
    move: move,
    open: open
  };

}).call(this);
